/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:52596be2-c5b7-4987-9f2c-d0a5e0f23aa1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_RM3qhvTWW",
    "aws_user_pools_web_client_id": "6o3fgjk5n89uk9tpnkut5a47in",
    "oauth": {
        "domain": "reactamplifyauthee7704f4-ee7704f4-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.youtube.com/",
        "redirectSignOut": "https://master.d3hcz947mft8bp.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
