/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:d19301ab-789c-48c8-a7ee-c1cfd924405d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_4NPyRwVuL",
    "aws_user_pools_web_client_id": "38ll8e80vhc8m705c2mq82lr2m",
    "oauth": {
        "domain": "testamplify8be341a2-8be341a2-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
